language: node_js
sudo: false
node_js: stable
script:
- npm run clean
branches:
  only:
  - master
install:
- npm install -g hexo
deploy:
- provider: script
  script: script/deploy
  skip_cleanup: true
  on:
    tags: false